"use client";

import { useState } from 'react';
import './globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [count, setCount] = useState(0);

  const handleClick = () => {
    setCount(prevCount => prevCount + 1);
  };

  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <pre>This is texts from the root layout file. </pre>

        <div>
          <div>root layout count: {count}</div>
          <button
            onClick={handleClick}
          >
            + increment
          </button>
        </div>

        {children}
      </body>
    </html>
  )
}
